---
- name: disable system tor
  systemd:
    name: tor.service
    enabled: false
    state: stopped
  become: true
- name: install stem from backports
  apt:
    pkg: python-stem
    state: latest
    default_release: buster-backports
  become: true
  notify: restart onionperf
- name: install onionperf dependencies
  apt:
    name: "{{ packages }}"
    update_cache: yes
    state: latest
  vars:
    packages:
    - git
    - cmake
    - make
    - libigraph0-dev
    - libglib2.0-dev
    - python-dev
    - libglib2.0-0
    - libigraph0v5
    - python-ipaddress
    - python-lxml
    - python-matplotlib
    - python-netifaces
    - python-networkx
    - python-nose
    - python-numpy
    - python-scipy
  become: true
  notify: restart onionperf
- name: clone onionperf repository
  git:
    repo: 'https://git.torproject.org/onionperf.git'
    dest: "{{ onionperf_clone_directory }}"
    version: "{{ op_version }}"
  become: true
  register: oprepo
- name: clone tgen repository
  git:
    repo: 'https://github.com/shadow/tgen.git'
    dest: "{{ tgen_clone_directory }}"
    version: "{{ tgen_version }}"
  become: true
  register: tgenrepo
- name: create tgen build dir
  file:
    state: directory
    path: "{{ tgen_clone_directory }}/build"
  become: true
- name: build tgen
  command: "{{ item }} chdir={{ tgen_clone_directory }}/build"
  with_items:
    - cmake ..
    - make
  when: tgenrepo.changed
  become: true
- name: install tgen
  file:
    src: "{{ tgen_clone_directory }}/build/tgen"
    dest: "/usr/bin/tgen"
    state: link
  when: tgenrepo.changed
  become: true
- name: build and install onionperf
  command: "{{ item }} chdir={{ onionperf_clone_directory }}"
  with_items:
    - python setup.py install
  when: oprepo.changed
  become: true
- name: create onionperf user
  user:
    name: onionperf
    state: present
    comment: OnionPerf Service User
    home: /srv/onionperf.torproject.net
  become: true
- name: install onionperf service file
  template:
    src: files/onionperf.service.j2
    dest: /etc/systemd/system/onionperf.service
  notify: restart onionperf
  become: true
- name: install apache2
  apt:
    name: apache2
  become: true

